version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123aaa
      MYSQL_DATABASE: homelette
      MYSQL_USER: homelette_user
      MYSQL_PASSWORD: 123aaa
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network

  flask-api:
    build: 
      context: ./src/backend-api
      dockerfile: Dockerfile
    container_name: flask-api
    restart: always
    depends_on:
      - mariadb
      - redis
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: "true"
      DATABASE_URL: "mysql+pymysql://homelette_user:123aaa@mariadb/homelette"
      JWT_SECRET_KEY: "super-secret-key-change-in-production"
      FLASK_ENV: "development"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - ./src/backend-api:/app
      - uploads_data:/app/uploads
    networks:
      - network

  flask-socket:
    build: 
      context: ./src/backend-socket
      dockerfile: Dockerfile
    container_name: flask-socket
    restart: always
    depends_on:
      - mariadb
      - redis
    ports:
      - "5002:5000"
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: "true"
      DATABASE_URL: "mysql+pymysql://homelette_user:123aaa@${MARIADB_IP:-mariadb}/homelette"
      JWT_SECRET_KEY: "super-secret-key-change-in-production"
      FLASK_ENV: "development"
      REDIS_URL: "redis://${REDIS_IP:-redis}:6379/0"
      MARIADB_IP: "${MARIADB_IP:-mariadb}"
      REDIS_IP: "${REDIS_IP:-redis}"
    volumes:
      - ./src/backend-socket:/app
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mariadb_data:
  uploads_data: