version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123aaa
      MYSQL_DATABASE: homelette
      MYSQL_USER: homelette_user
      MYSQL_PASSWORD: 123aaa
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - homelette-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - homelette-network

  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    depends_on:
      - mariadb
      - redis
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: "true"
      DATABASE_URL: "mysql+pymysql://homelette_user:123aaa@mariadb/homelette"
      JWT_SECRET_KEY: "super-secret-key-change-in-production"
      FLASK_ENV: "development"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
    networks:
      - homelette-network

networks:
  homelette-network:
    driver: bridge

volumes:
  mariadb_data: 