name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: backend/Dockerfile
        failure-threshold: warning
    
    - name: Validate docker-compose.yml
      run: |
        docker compose -f backend/docker-compose.yml config -q
    
  docker-build:
    runs-on: ubuntu-latest
    needs: docker-lint
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Flask image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: false
        tags: homelette-flask:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker Compose
      run: |
        cd backend
        docker compose up -d
        
        # Wait for containers to start
        sleep 20
        
        # Check if containers are running
        if [ "$(docker-compose ps -q flask | wc -l)" -eq 0 ]; then
          echo "Flask container failed to start"
          docker compose logs
          exit 1
        fi
        
        if [ "$(docker-compose ps -q mariadb | wc -l)" -eq 0 ]; then
          echo "MariaDB container failed to start"
          docker compose logs
          exit 1
        fi
        
        # Check if Flask is responding
        FLASK_STATUS=$(docker-compose exec -T flask curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/ || echo "Failed")
        if [ "$FLASK_STATUS" != "404" ] && [ "$FLASK_STATUS" != "200" ]; then
          echo "Flask API is not responding correctly (status: $FLASK_STATUS)"
          docker compose logs flask
          exit 1
        fi
        
        echo "Docker Compose test successful!"
        docker compose down
      continue-on-error: true 