name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
    # 检出代码
    - uses: actions/checkout@v4

    # 设置 Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 安装依赖
    - name: Install dependencies
      run: npm install
      working-directory: ./Homelette

    # 测试 Expo 启动
    - name: Test Expo start
      run: |
        cd ./Homelette
        npx expo start --no-dev --no-open &
        sleep 15 # 给服务器一些时间来启动
        curl --fail http://localhost:8081 || (echo "Expo failed to start" && exit 1)
      working-directory: ./Homelette
